version: 0.2

phases:
  pre_build:
    commands:
      - echo "Fetching secrets from Secrets Manager"
      - aws secretsmanager get-secret-value --secret-id $SECRETS_ARN --query SecretString --output text > secrets.json
      - jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' secrets.json >> .env
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f docker/Dockerfile --platform linux/amd64 -t kenzie_ecr_repo .
      - docker tag kenzie_ecr_repo:latest $REPOSITORY_URI:latest
      - docker tag kenzie_ecr_repo:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Zipping deployment files, including app code with updated file paths..."
      - zip -r deployment-package.zip deploy/appspec.yml deploy/scripts/ src/ docker/
  post_build:
    commands:
      - echo "Moving appspec.yml to root..."
      - cp deploy/appspec.yml .  # Move appspec.yml to the root
      - cp -r deploy/scripts .   # Move scripts if needed
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $REPOSITORY_URI:latest
      - echo "Uploading deployment package to S3..."
      - aws s3 cp deployment-package.zip s3://kenzie-pipeline-artifacts/deployment-package.zip
artifacts:
  files:
    - deployment-package.zip
    - appspec.yml
    - src/**/*
    - docker/**/*
    - terraform/**/*
    - deploy/*