version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deployment/scripts

hooks:
  BeforeInstall:
    - location: deploy/scripts/stop_existing_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/scripts/start_new_container.sh
      timeout: 300
      runas: root